config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :customers,skip: [:passwords,],controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }
    
  root 'customer/homes#top'
  get 'about' => 'customer/homes#about'

  scope module: :customer do
    resources :items, only: [:index, :show]

    get 'customers/my_page' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    patch 'customers' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/comfirm' => 'orders#comfirm'

    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  namespace :admin do
    get '/' => 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    patch 'orders/:order_id/order_details/:id' => 'order_details#update'
    resources :orders, only: [:index ,:show, :update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items
  has_many :orders
  has_many :addresses

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    attachment :image
    
    has_many :cart_items
    has_many :order_details
    belongs_to :genre

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, comfirm: 1, in_production: 2, ready_to_ship: 3, shipped: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { couldnt_make: 0, waiting_for_production: 1, in_production: 2, completed: 3 }

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
        @items = Item.all
        @items = @items.where('name LIKE ?', "%#{params[:search]}%") if params[:search].present?
    end

    def new
        @item = Item.new
    end

    def create
        @item = Item.new(item_params)
        @item.save
        redirect_to admin_item_path(@item)
    end

    def show
    end

    def edit
    end

    def update
    end

    private

    def item_params
       params.require(:item).permit(:image,:name,:introduction,:genre_id,:price,:is_active)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    before_action :check_admin, only: [:index, :show]

    def index
        @orders = Order.all
    end

    def show
        @order = Order.find(params[:id])
        @order_details = OrderDetail.where(order_id: @order.id)
    end

    def update
        @order = Order.find(params[:id])
        if params[:order][:status] == 'comfirm'
            @order.update(status: (Order.statuses[params[:order][:status].to_sym]).to_i)
            order_details = OrderDetail.where(order_id: @order.id)
            order_details.each do |order_detail|
                order_detail.update(making_status: 1)
            end
            redirect_to admin_orders_path
        else
            @order.update(status: params[:order][:status].to_i)
            redirect_to admin_orders_path
        end
    end

    private

    def check_admin
        unless admin_signed_in?
            redirect_to root_path
        end
    end

    def order_params
        params.require(:order).permit(:id, :status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
    before_action :comfirm_order_items, only: [:new]

    def new
        @order = Order.new
    end

    def comfirm
        @order_new = Order.new
        @order = Order.new
        @order.payment_method = params[:order][:payment_method].to_i
        @order.customer_id = current_customer.id
        @order.shipping_cost = 800
        @cart_items = CartItem.where(customer_id: current_customer.id)
        if  params[:order][:address_option] == "0"
            @order.postal_code = current_customer.postal_code
            @order.address = current_customer.address
            @order.name = current_customer.last_name + current_customer.first_name
            render :comfirm
        elsif params[:order][:address_option] == "1"
            address = Address.find(params[:order][:address_id])
            @order.postal_code = address.postal_code
            @order.address = address.address
            @order.name = address.name
            render :comfirm
        elsif params[:order][:address_option] == "2"
            @order.postal_code = params[:order][:postal_code]
            @order.address = params[:order][:address]
            @order.name = params[:order][:name]
            render :comfirm
        end
    end

    def complete
    end

    def create
        @order = Order.new(order_params)
        @order.save
        cart_items = CartItem.where(customer_id: current_customer.id)
        cart_items.each do |cart_item, order_detail|
            order_detail  = OrderDetail.new
            order_detail.order_id = @order.id
            order_detail.item_id = cart_item.item_id
            order_detail.price = cart_item.item.price
            order_detail.amount = cart_item.amount
            order_detail.save
        end
        @cart_items = CartItem.where(customer_id: current_customer.id)
        @cart_items.destroy_all
        redirect_to orders_complete_path
    end

    def index
    end

    def show
    end

    private

    def comfirm_order_items
        if current_customer.cart_items.exists?
        else
            redirect_to items_path
        end
    end

    def order_params
        params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping_cost, :payment_method, :total_payment)
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/helpers/customer/items_helper.rb
module Customer::ItemsHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="m-5 h4 bg-light">
      注文情報一覧
    </div>
  </div>

  <div class="row">
    <table class="table table-bordered">
      <thead>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </thead>
      <% @orders.each do |order| %>
      <tbody>
        <td><%= link_to (l order.created_at), admin_order_path(order), class: "text-dark" %></td>
        <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
        <% order_details = OrderDetail.where(order_id: order.id) %>
        <% count = 0 %>
        <% order_details.each { |order| count += order.amount } %>
        <td><%= count %></td>
        <td><%= Order.statuses_i18n[order.status] %></td>
      </tbody>
      <% end %>
    </table>
  </div>

</div>

app/views/admin/orders/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-2"></div>
    <div class="col-2 bg-light h4">注文履歴詳細</div>
  </div>

  <div class="row">
    <div class="col-2 mt-5 ml-3">
      <div class="my-1">購入者</div>
      <div class="my-1">注文日</div>
      <div class="my-1">発送先</div>
      <div class="my-1">支払い方法</div>
      <div class="my-2">注文ステータス</div>
    </div>

    <div class="col-6 mt-5">
      <div class=" my-1"><%= @order.customer.last_name %><%= @order.customer.first_name %></div>
      <div class=" my-1"><%= l @order.created_at, format: :short %></div>
      <div class=" my-1"><%= @order.postal_code %><span>　　</span><%= @order.address %><span>　　</span><%= @order.name %></div>
      <div class=" my-1"><%= Order.payment_methods_i18n[@order.payment_method] %></div>
      <div class=" my-1">
        <%= form_with model: @order, url: "/admin/orders/#{@order.id}", method: :patch, local: true do |f| %>
          <%= f.hidden_field :id, value: @order.id %>
          <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
          <%= f.submit "変更", class: "btn btn-success ml-3" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row  mt-5">
    <div class="col-8">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th scope="col">製作ステータス</th>
          </tr>
        </thead>
        <% @order_details.each do |order_detail| %>
          <tbody>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.item.with_tax_price %></td>
              <td><%= order_detail.amount %></td>
              <td><%= order_detail.amount * order_detail.item.with_tax_price %></td>
              <td>
                <%= form_with model: order_detail, url: "/admin/orders/#{@order.id}/order_details/#{order_detail.id}", method: :patch, local: true do |f| %>
                  <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
                  <%= f.submit "更新", class: "btn btn-success ml-3" %>
                <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>

    <div class="col">
      <div class=h6>合計金額</div>
      <div class=h6>送料</div>
      <div class=h6>請求金額合計</div>
    </div>

    <div class="col">
      <div><%= @order.total_payment %>円</div>
      <div><%= @order.shipping_cost %>円</div>
      <div><%= @order.total_payment + @order.shipping_cost %>円</div>
    </div>
  </div>

</div>